### ISSUE TITLE
error in example code

### ISSUE THREAD

**Issue by sbbmu** [SomaLogic/SomaDataIO#16] opened 2022-03-08 01:15 UTC
An error occurred when running the following code from the example. Please help! Thank you!

```
library(SomaDataIO)
library(tidyverse)
f <- system.file("example", "example_data.adat", package = "SomaDataIO", mustWork = TRUE)
my_adat <- read_adat(f)

is.intact.attributes(my_adat)

# Prepare data set for analysis
cleanData <- example_data %>%
  mutate(Group = as.numeric(factor(Sex)) - 1)    # map Sex -> 0/1
```
```
x Attributes has only 3 entries: 'names', 'row.names', 'class'
 Error in mutate.soma_adat(., Group = as.numeric(factor(Sex)) - 1) : 
is.intact.attributes(.data) is not TRUE
```

It looks like line `.data <- NextMethod()` in the `mutate.soma_adat()` function uses `mutate.data.frame()` which stripped the attributes.
```
> .data=example_data
> .data <- rn2col(.data, ".mutate_rn")
> names(attributes(.data))
[1] "names"       "class"       "row.names"   "spec"        "Header.Meta" "Col.Meta"    "file.specs"  "row.meta"   
>     .data <- dplyr:::mutate.data.frame(.data, .keep="all")
> names(attributes(.data))
[1] "names"     "row.names" "class"    
```
This resulted in the error in the next 2 lines.
```
> .data <- col2rn(.data, ".mutate_rn")
> stopifnot(is.intact.attributes(.data))

x Attributes has only 3 entries: 'names', 'row.names', 'class'
[1] FALSE
```
```
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1    stringr_1.4.0    dplyr_1.0.8      purrr_0.3.4      readr_2.1.2      tidyr_1.2.0      tibble_3.1.6     ggplot2_3.3.5   
 [9] tidyverse_1.3.1  SomaDataIO_5.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8        lubridate_1.8.0   prettyunits_1.1.1 ps_1.6.0          assertthat_0.2.1  rprojroot_2.0.2   utf8_1.2.2       
 [8] cellranger_1.1.0  R6_2.5.1          backports_1.4.1   reprex_2.0.1      httr_1.4.2        pillar_1.7.0      rlang_1.0.1      
[15] readxl_1.3.1      curl_4.3.2        rstudioapi_0.13   callr_3.7.0       desc_1.4.0        devtools_2.4.3    bit_4.0.4        
[22] munsell_0.5.0     broom_0.7.12      compiler_4.1.1    modelr_0.1.8      xfun_0.29         pkgconfig_2.0.3   pkgbuild_1.3.1   
[29] tidyselect_1.1.2  fansi_1.0.2       crayon_1.5.0      tzdb_0.2.0        dbplyr_2.1.1      withr_2.4.3       brio_1.1.3       
[36] grid_4.1.1        jsonlite_1.8.0    gtable_0.3.0      lifecycle_1.0.1   DBI_1.1.2         magrittr_2.0.2    scales_1.1.1     
[43] stringi_1.7.6     cli_3.2.0         vroom_1.5.7       cachem_1.0.6      fs_1.5.2          remotes_2.4.2     testthat_3.1.2   
[50] xml2_1.3.3        ellipsis_0.3.2    generics_0.1.2    vctrs_0.3.8       tools_4.1.1       bit64_4.0.5       glue_1.6.2       
[57] hms_1.1.1         processx_3.5.2    pkgload_1.2.4     parallel_4.1.1    fastmap_1.1.0     colorspace_2.0-3  sessioninfo_1.2.2
[64] rvest_1.0.2       memoise_2.0.1     knitr_1.37        haven_2.4.3       usethis_2.1.5    

```

**Comment by stufield** [comment] 2022-03-08 03:42
Hi @sbbmu , thanks for submitting this issue.This looks to be a duplicate of #15.

We are currently working on a next release of `SomaDataIO` that solves this issue, which results from the new `dplyr v1.0.8`.

In the meantime the quickest workaround is to backrev to `dplyr v1.0.6` (and those versions suggested in the `README`).

**Comment by sbbmu** [comment] 2022-03-08 19:25
Nice! Thank you for the suggestions. Sorry, I didn't see #15. I will try it.

**Comment by stufield** [comment] 2022-03-08 23:35
Let's keep this open so that others see it more easily, at least until the next release comes out.

**Comment by stufield** [comment] 2022-03-30 18:09
Closing now that `v5.3.0` is released

**Closed by stufield** 2022-03-30 18:09 UTC
Labels: bug, duplicate
